export const menuData = [
    {
        category: 'salad',
        name: 'Radish Green Salad',
        desc: 'Make use of all the wonderful curly, coral lettuce that we had growing in the garden.',
        price:'RM 10.80',
        image: require('../images/radishGreenSalad.png'),
    },
    {
        category: 'salad',
        name: 'Honey Lime Rainbow Fruit Salad',
        desc: 'Made with beautiful blend of delicious fruits and a simple dressing to compliment it.',
        price:'RM 11.80',
        image: require('../images/honeyLimeRainbow.png'),
    },
    {
        category: 'salad',
        name: 'Caesar Salad',
        desc: 'The crowd-pleasing salad of crisp romaine leaves, crunchy croutons, and a little or a lot of anchovy.',
        price:'RM 12.80',
        image: require('../images/caesarSalad.png'),
    },
    {
        category: 'mainCourse',
        name: 'Chicken Chop',
        desc: 'Juicy Fried Chicken Chop paired with Coleslaw, Fries, and a Sunny-Side Up Egg.',
        price:'RM 18.50',
        image: require('../images/chickenChop.jpg'),
    },
    {
        category: 'mainCourse',
        name: 'Fish and Chips',
        desc: 'Fried Dory Fish with Crunchy Wedges paired with the Homemade Tartar Sauce.',
        price:'RM 19.00',
        image: require('../images/fishAndChips.jpg'),
    },
    {
        category: 'mainCourse',
        name: 'Ribeye Steak',
        desc: 'Ribeye Steak with Garlic Butter cooked to perfect Medium Rare and served with Roasted Potato and Green Beans.',
        price:'RM 40.00',
        image: require('../images/ribeyeSteak.jpg'),
    },
    {
        category: 'mainCourse',
        name: 'Lamb Chop',
        desc: 'Juicy Pan-Seared Lamb Chops with Cipollini Onions.',
        price:'RM 37.00',
        image: require('../images/lambChop.jpg'),
    },
    {
        category: 'pizza',
        name: 'Hawaiian Supreme',
        desc: 'Pizza with tomato sauce, chicken meat, chicken loaf, pineapples, mozzarella cheese.',
        price:'RM 30.00',
        image: require('../images/hawaiianSupreme.png'),
    },
    {
        category: 'pizza',
        name: 'Chicken Supreme',
        desc: 'Pizza with tomato sauce, chicken meat, chicken salami, chicken loaf, mushrooms, capsicums, onions, mozzarella cheese, tomatoes.',
        price:'RM 30.00',
        image: require('../images/chickenSupreme.png'),
    },
    {
        category: 'pizza',
        name: 'Blazing Seafood',
        desc: 'Pizza with spicy sweet sour sauce, tuna, crabsticks, pineapples, capsicums, onions, mozzarella cheese.',
        price:'RM 30.00',
        image: require('../images/blazingSeafood.png'),
    },
    {
        category: 'pizza',
        name: 'Triple Chicken',
        desc: 'Pizza with thousand island sauce, chicken rolls, chicken meat, chicken salami, mushrooms, tomatoes, onions, mozzarella cheese.',
        price:'RM 30.00',
        image: require('../images/tripleChicken.png'),
    },
    {
        category: 'pasta',
        name: 'Baked Feta Pasta',
        desc: 'Cherry tomatoes and a whole block of feta are baked until soft and melty, then tossed with garlic, basil and cooked noodles for a beautifully cheesy dish.',
        price:'RM 15.00',
        image: require('../images/bakedFetaPasta.png'),
    },
    {
        category: 'pasta',
        name: 'Pasta with Garlic and Cheese',
        desc: 'Kind of like a deconstructed pesto, using parsley instead of basil.',
        price:'RM 16.70',
        image: require('../images/pastaGarlicCheese.png'),
    },
    {
        category: 'pasta',
        name: 'Pasta with Fresh Tomato Sauce',
        desc: 'Romas (aka plum tomatoes) fit the bill, but there are plenty of heirlooms with a similar flesh-to-seed ratio.',
        price:'RM 20.15',
        image: require('../images/pastaTomatoSauce.png'),
    },
    {
        category: 'burger',
        name: 'Whooper',
        desc: 'A real meaty flame-grilled Whopper® beef patty, topped with tangy pickles, ketchup, fresh tomatoes, crisp lettuce and fresh onions, finished with creamy mayo , and served on a toasted 5" sesame seed bun.',
        price:'RM 15.00',
        image: require('../images/whooper.png'),
    },
    {
        category: 'burger',
        name: 'Whooper Jr',
        desc: 'A mouth-watering, flame-grilled beef patty topped with fresh tomatoes, crisp lettuce, tangy pickles and crunchy onions, served on a toasted sesame seed bun and flavored with creamy mayo and ketchup.',
        price:'RM 18.00',
        image: require('../images/whooperJr.png'),
    },
    {
        category: 'burger',
        name: 'Long Cheesy Onion Beef',
        desc: 'Featuring 2 pieces of our signature flame-grilled beef patties topped with Nachos Cheese sauce, mayonnaise, mustard, pickles and fresh onions served between two long sesame seed buns.',
        price:'RM 22.00',
        image: require('../images/cheesyOnionBeef.png'),
    },
    {
        category: 'burger',
        name: 'Double Cheeseburger',
        desc: 'Make room for our Double Cheeseburger, two signature flame-grilled beef patties topped with a simple layer of melted American cheese, crinkle cut pickles, yellow mustard, and ketchup on a toasted sesame seed bun.',
        price:'RM 26.00',
        image: require('../images/doubleCheeseburger.png'),
    },
    {
        category: 'coffeeTea',
        name: 'Caffe Latte',
        desc: 'Espresso topped with Velvety Smooth Steamed Milk.',
        price:'RM 12.00',
        image: require('../images/latte.png'),
    },
    {
        category: 'coffeeTea',
        name: 'Mocha',
        desc: 'An Indulgent Blend of Espresso & Hot Chocolate topped with Velvety Steamed Milk.',
        price:'RM 10.00',
        image: require('../images/mocha.png'),
    },
    {
        category: 'coffeeTea',
        name: 'Cappuccino',
        desc: 'Espresso with Smooth Steamed Milk & finished with a Light Drizzle of Chocolate.',
        price:'RM 12.00',
        image: require('../images/cappuccino.png'),
    },
    {
        category: 'coffeeTea',
        name: 'Butterfly Pea Tea',
        desc: 'An Earthy, Woody Tea with an Exquisite Blue Tinge and Distinct Floral Aroma.',
        price:'RM 9.00',
        image: require('../images/butterflyPeaTea.png'),
    },
    {
        category: 'coffeeTea',
        name: 'Lemongrass Ginger Tea',
        desc: 'Fragrant and Aromatic, this is refreshing lemongrass-flavoured tea with a slight trace of ginger.',
        price:'RM 9.00',
        image: require('../images/lemongrassGinger.png'),
    },
    {
        category: 'fruitJuice',
        name: 'Fig Butterfly',
        desc: 'Fig juice with an exquisite pink tinge.',
        price:'RM 11.00',
        image: require('../images/figButterfly.png'),
    },
    {
        category: 'fruitJuice',
        name: 'Mango Tango',
        desc: 'A rich mixture of mango, passion fruit and apple.',
        price:'RM 10.00',
        image: require('../images/mangoTango.png'),
    },
    {
        category: 'fruitJuice',
        name: 'Golden Passion',
        desc: 'Sweet pineapple, passion fruit, guava with a touch of mint leaves        .',
        price:'RM 10.00',
        image: require('../images/goldenPassion.png'),
    },
    {
        category: 'fruitJuice',
        name: 'Pink Lady',
        desc: 'Dragon Fruit, Pear, Grapes, topped with mint leaf.',
        price:'RM 10.00',
        image: require('../images/pinkLady.png'),
    },
    {
        category: 'fruitJuice',
        name: 'Greenty Minty',
        desc: 'A mix of green apple and kiwi with mint leaf and lime.',
        price:'RM 10.00',
        image: require('../images/greentyMinty.png'),
    },
    {
        category: 'smoothies',
        name: 'Chocolate Smoothie',
        desc: 'Sweet and Chocolaty, a Perfect Drink for your Date.',
        price:'RM 13.00',
        image: require('../images/chocolateSmoothie.jpg'),
    },
    {
        category: 'smoothies',
        name: 'Dragon Fruit Smoothie',
        desc: 'Made with Fresh Dragon Fruit, Tasty and Hydrating!',
        price:'RM 13.00',
        image: require('../images/dragonFruitSmoothie.jpg'),
    },
    {
        category: 'smoothies',
        name: 'Banana Smoothie',
        desc: 'Healthy and Delicious! Nothing can go wrong with a Banana Smoothie!',
        price:'RM 13.00',
        image: require('../images/bananaSmoothie.jpg'),
    },
    {
        category: 'alcohol',
        name: 'Penfolds St.Henri Shiraz 2016',
        desc: 'Variety: Syrah/Shiraz\nVintage: 2016\nAppellation: Barossa Valley, Australia',
        price:'RM 160.00',
        image: require('../images/penfolds2016.png'),
    },
    {
        category: 'alcohol',
        name: 'Bollinger Special Cuvee Brut NV Champagne',
        desc: 'Variety: France\nVintage: 2020\nAppellation: Epernay',
        price:'RM 338.00',
        image: require('../images/bollinger.jpg'),
    },
    {
        category: 'alcohol',
        name: 'Taittinger Reserve Brut NV Champagne',
        desc: 'Variety: France\nVintage: 2020\nAppellation: Reims',
        price:'RM 338.00',
        image: require('../images/taittinger.jpg'),
    },
    {
        category: 'alcohol',
        name: 'Millaman Condor Merlot',
        desc: 'Variety: Merlot\nVintage: 2020\nAppellation: Chile',
        price:'RM 62.90',
        image: require('../images/millaman.jpg'),
    },
    {
        category: 'dessert',
        name: 'Cheesecake',
        desc: 'A creamy, sweet, and delicious no bake berry cheesecake.',
        price:'RM 8.00',
        image: require('../images/cheeseCake.jpg'),
    },
    {
        category: 'dessert',
        name: 'Snickers Pie',
        desc: 'Oreo crust, silky and airy chocolate filling and finished with chopped candy.',
        price:'RM 12.00',
        image: require('../images/snickersPie.jpg'),
    },
    {
        category: 'dessert',
        name: 'Texas Chocolate Cake',
        desc: 'Chocolate WASC, brownies, and double chocolate chip cookies.',
        price:'RM 20.00',
        image: require('../images/texasChocolate.jpg'),
    },
    {
        category: 'dessert',
        name: 'Mille Crepe Cake',
        desc: 'Twenty layers of thin coffee crepes layered together with coffee infused cream resulting in a cake packed full of coffee flavor and yet so smooth and delicate.',
        price:'RM 18.00',
        image: require('../images/milleCrepe.png'),
    },
>>>>>>> 5a180742df374a9415614b5ce479faeec124942a
];
